### ISSUE TITLE
Synchronous Dispatch Impression Event Causes Poor Performance

### ISSUE THREAD

**Issue by jerelevine** [optimizely/objective-c-sdk#349] opened 2018-12-13 06:32 UTC
https://github.com/optimizely/objective-c-sdk/blob/6ff2290d254a02db9523beb7718da6f59798a85c/OptimizelySDKCore/OptimizelySDKCore/Optimizely.m#L857-L867

I'm getting terrible performance on this call to the `dispatchImpressionEvent` call. I'm not sure if this or it's embedded slow synchronous calls can be made from a background thread but I believe it would greatly improve performance.

<img width="1040" alt="screen shot 2018-12-12 at 10 24 45 pm" src="https://user-images.githubusercontent.com/6404082/49919977-5e29a000-fe5d-11e8-8dc3-707b5ca72be2.png">

Please let me know if you have any further questions or concerns.

**Comment by thomaszurkan-optimizely** [comment] 2018-12-19 18:53
Hi @jerelevine, thanks for the feedback.  If you look a little deeper, we believe the issue is the sqlite call to save and query for the id.  We are reviewing how we want to solve this issue now.  Thanks again for bringing this to our attention.  I'll let you know when we have a solution.

**Comment by thomaszurkan-optimizely** [comment] 2019-02-15 00:50
This is fixed in the 3.0 release of the objective-c sdk.

**Closed as completed by thomaszurkan-optimizely** 2019-02-15 00:50 UTC
