### ISSUE TITLE
OPTLYHTTPRequestManager.m line 378

### ISSUE THREAD

**Issue by barfoon** [optimizely/objective-c-sdk#211] opened 2018-01-22 21:21 UTC
Not sure if this is still an issue in `1.5.0` but we are seeing the following crash in our logs:

OPTLYHTTPRequestManager.m line 378
`*** -[__NSArrayM setObject:atIndexedSubscript:]: index 2 beyond bounds [0 .. 0]`

![image](https://user-images.githubusercontent.com/1120510/35244980-10e45c8a-ff90-11e7-95b8-144dc3c93777.png)

![image](https://user-images.githubusercontent.com/1120510/35245025-34f30b3a-ff90-11e7-865a-0aabd0277cc7.png)

I have only been able to see this once and it happened on launch of the application.

**Comment by kellyroach-optimizely** [comment] 2018-01-26 18:16
An OPTLYHTTPRequestManager.m NSRangeException issue was fixed in 1.5.0 .
Optimizely's objective-c-sdk 1.5.0 release contains this fix:

    Bug Fixes:
    Crash caused by Fatal Exception: NSRangeException in OPTLYHTTPRequestManager.m.
    This crash occurred during a backoff retry in a datafile download
    or event dispatch because data strutures that were not threadsafe
    (used only for testing) were being modified. To resolve this, the
    data structures were wrapped in a flag and are only modifiable if
    unit tests are running.
    https://github.com/optimizely/objective-c-sdk/blob/1.5.0/CHANGELOG.md

**Closed as completed** 2018-04-16 22:31 UTC
